import "server-only";

import { createHash, randomBytes, timingSafeEqual } from "node:crypto";

import { isWellFormedShareToken } from "@/lib/validation/inspections";

/**
 * Public share-link tokens for completed inspections (spec section 13).
 *
 * THE INVARIANT: the database only ever sees a SHA-256 digest. The plaintext
 * token exists in exactly two places -- the URL the customer holds, and the
 * one-time reveal shown to staff at generation. It is never persisted, never
 * logged, and cannot be recovered from a database dump, so a leak of the
 * `vehicle_inspections` table yields no working links.
 *
 * Token shape: 32 cryptographically random bytes rendered base64url, which is
 * 43 characters with no padding. Deliberately NOT a UUID: a UUIDv4 carries only
 * 122 bits and is generated by a code path used for guessable, enumerable
 * identifiers elsewhere in the app.
 */

/** Raw entropy in bytes. 32 bytes = 256 bits = 43 base64url characters. */
const TOKEN_BYTES = 32;

/** Digest length the `set_inspection_share` RPC requires (octet_length = 32). */
const DIGEST_BYTES = 32;

/**
 * Mint a new share token.
 *
 * Returns the plaintext (to be shown to staff exactly once and put in the
 * customer's URL) alongside the hex-encoded digest to store. The caller must
 * never persist or log `token`.
 */
export function generateShareToken(): { token: string; tokenHashHex: string } {
  const token = randomBytes(TOKEN_BYTES).toString("base64url");
  return { token, tokenHashHex: hashShareToken(token) };
}

/**
 * Hash a presented token into the `\x…` bytea literal PostgREST accepts.
 *
 * The digest is taken over the token's ASCII characters (not the decoded
 * bytes), so generation and lookup agree on exactly one representation. Both
 * `generateShareToken` and the public route funnel through this function --
 * if they ever diverged, every link would silently 404.
 */
export function hashShareToken(token: string): string {
  const digest = createHash("sha256").update(token, "utf8").digest();
  return `\\x${digest.toString("hex")}`;
}

/**
 * Hash a token that arrived from an untrusted source (a URL path segment).
 *
 * Returns `null` for anything that is not exactly 43 base64url characters, so
 * a malformed token costs no database round trip. The caller must render the
 * SAME "not available" response for `null` as it does for a token that simply
 * does not resolve -- otherwise the shape of the reply becomes an oracle that
 * distinguishes "wrong format" from "revoked".
 */
export function hashPresentedShareToken(token: unknown): string | null {
  if (!isWellFormedShareToken(token)) return null;
  return hashShareToken(token as string);
}

/**
 * Constant-time comparison of two hex digests.
 *
 * Not used on the lookup path (Postgres does that comparison), but exported for
 * any future in-process check so a timing side channel is not reintroduced by
 * a casual `===`.
 */
export function digestsMatch(a: string, b: string): boolean {
  const bufA = Buffer.from(a.replace(/^\\x/, ""), "hex");
  const bufB = Buffer.from(b.replace(/^\\x/, ""), "hex");
  if (bufA.length !== DIGEST_BYTES || bufB.length !== DIGEST_BYTES) return false;
  return timingSafeEqual(bufA, bufB);
}

/**
 * Absolute path for a share link. Locale-prefixed because `localePrefix` is
 * "always" in i18n/routing.ts, and the middleware exemption matches the
 * de-localized `/i/<token>`.
 */
export function shareTokenPath(locale: string, token: string): string {
  return `/${locale}/i/${token}`;
}
